### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by numericlee** [markhliu/DGAI#1]
Mark, loving your course so far.

I am working through Chapter 6 (Cycle GAN) 

Does this link still work?
https://gattonweb.uky.edu/faculty/lium/ml/hair.zip

are other trained models available (for example the glasses generator).  the notebook crashes even when I dial down the batch size, features, etc.

If I buy the ebook, will it include the pretrained models?

**Comment by markhliu** [comment]
I am working on revising chapters 6-10 now, so things may take a couple of weeks to finalize. I just uploaded the hair.zip file. Try it now. It should work. 

My book will include all pre-trained models. I'll provide a link to my website for readers to download.

**Comment by numericlee** [comment]
thanks so much, Mark , one more question. 
I am getting an error running  VAE()  with a CPU. is a GPU required for any portions of the course?
AssertionError: Torch not compiled with CUDA enabled

**Comment by markhliu** [comment]
No. Just slower. It sounds like you installed pytorch without CUDA support. https://pytorch.org/ has instructions for how to install pytorch with cuda support. Can you tell me which code block gives you that error so maybe I can fix it? Read my appendix to install PyTorch with CPU if you don't have CUDA-enabled GPU.

**Comment by numericlee** [comment]
Thanks. Reviewing your ebook now.. Installed pytorch without CUDA support since I have a CPU. Alll the notebooks to this block ran ok

vae=VAE().to(device)
lr=1e-4 
optimizer=torch.optim.Adam(vae.parameters(),
                           lr=lr,weight_decay=1e-5)


Also FYI I had a separate issue with the glasses module (notebook 5) . when I reduced imgsize from 256x256 to  128x128 (to run on my 16GB machine) , in training the Generator() which added noise always output in Bx1x256x256 which caused a concatenation error.

**Comment by markhliu** [comment]
Thanks for agreeing to review my eBook. 
I tried VAE on a computer with CPU only just now and no issue at all. 
In PyTorch, it's very tricky to change image size in a neural network. You need to make sure the size matches from one layer to the next. Just changing size in one layer doesn't work.
