### ISSUE TITLE
Question about first GAN in book

### ISSUE THREAD

**Issue by m7mdhka** [markhliu/DGAI#2]
Hello,
I want to ask about the first GAN we have trained on the book, 
Is it better to train the discriminator in both fake and real?
I mean is to merge the fake samples with real samples in the same data loader, and then shuffle them and train the discriminator after.
If no, why we train the discriminator on real first, then on fake samples?

**Comment by markhliu** [comment]
It doesn't matter. Merging real and fake samples when  training won't help. You'll get the same result.
